_site:
  output: _site

collections:
  homepage:
    output: true
    path: content/homepage.md
    editor:
      preview: true
      fields:
        - type: text
          label: Page Title
          name: title
        - type: markdown
          label: Main Content
          name: body
