backend:
  name: github
  repo: yamkel-cell/sutiyam
  branch: main
  auth_type: implicit
  app_id: Ov23lihUeX8y5I795EPw

media_folder: "img"  # Where uploaded images are stored in your repo
public_folder: "/img/uploads"  # Path to access images

collections:
  - name: "homepage"
    label: "Homepage Content"
    files:
      - file: "index.html"
        label: "Main Page"
        name: "main_page"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Main Content", name: "body", widget: "text" }
