backend:
  name: github
  repo: yamkel-cell/sutiyam
  branch: main

local_backend: true  # optional, for local testing

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Main Image", widget: "image" }
      - { name: "thumbnails", label: "Gallery Images", widget: "list", field: { name: "thumb", label: "Thumbnail", widget: "image" } }
      - { name: "alt", label: "Alt Text", widget: "string" }
      
      # to homepage
      
  - name: "homepage"
    label: "Homepage Content"
    delete: false
    files:
      - file: "content/homepage.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Body", widget: "text" }
