backend:
  name: github
  repo: yamkel-cell/sutiyam
  branch: main
  auth_type: implicit
  app_id: <GITHUB-OAUTH-APP-ID>
  base_url: https://api.netlify.com
  auth_endpoint: auth


media_folder: "img"
public_folder: "/img"

collections:
  - name: "homepage"
    label: "Homepage Content"
    files:
      - file: "content/homepage.md"  # point to the correct markdown file
        label: "Main Page"
        name: "main_page"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Main Content", name: "body", widget: "markdown" }
