backend:
  name: github
  repo: yamkel-cell/sutiyam  # GitHub repo
  branch: main
  base_url: https://api.netlify.com
  site_domain: www.sutiyam.online
  auth_endpoint: https://auth.netlify.com


local_backend: true  # optional, for local testing

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Main Image", widget: "image" }
      - { name: "thumbnails", label: "Gallery Images", widget: "list", field: { name: "thumb", label: "Thumbnail", widget: "image" } }
      - { name: "alt", label: "Alt Text", widget: "string" }

    # Collection products
  - name: "collection"
    label: "Collection Products"
    folder: "content/collection-products"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Main Image", widget: "image" }
      - { name: "alt", label: "Alt Text", widget: "string" }
      - { name: "price", label: "Price", widget: "number" }
      - { name: "sizes", label: "Sizes", widget: "list", default: ["28", "30", "32"] }
      - { name: "thumbnails", label: "Thumbnail Images", widget: "list", field: {label: "Thumbnail", name: "thumb", widget: "image"} }
      - { name: "rating", label: "Rating (0-5)", widget: "number", min: 0, max: 5, step: 1 }
      - { name: "description", label: "Description", widget: "text" }
      
      # to homepage
      
  - name: "homepage"
    label: "Homepage Content"
    delete: false
    files:
      - file: "content/homepage.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Body", widget: "markdown" }

      # Reviews
  
  - name: "reviews"
    label: "Customer Reviews"
    folder: "content/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "name", label: "Customer Name", widget: "string" }
      - { name: "rating", label: "Rating (0-5)", widget: "number", min: 0, max: 5, step: 1 }
      - { name: "image", label: "Customer Image", widget: "image", required: false }
      - { name: "body", label: "Review Message", widget: "markdown", required: true }
