backend:
  name: github
  repo: yamkel-cell/sutiyam
  branch: main
  base_url: https://www.sutiyam.online

media_folder: "img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
