backend:
  name: github
  repo: your-username/your-repo-name
  branch: main
  base_url: https://your-auth-app.netlify.app  # We'll configure this below

media_folder: "img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
