backend:
  name: github
  repo: yamkel-cell/sutiyam       # GitHub repo
  branch: main
  auth_type: pkce                 # PKCE flow for Auth0
  base_url: https://www.sutiyam.online   
  auth_endpoint: /.netlify/functions/auth

media_folder: "img"
public_folder: "/img"

collections:
  - name: "homepage"
    label: "Homepage Content"
    files:
      - file: "content/homepage.md"  # point to the correct markdown file
        label: "Main Page"
        name: "main_page"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Main Content", name: "body", widget: "markdown" }
