name: Add Review
on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
      message:
        required: true
        type: string
      rating:
        required: false
        type: string
      image:
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  add_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create new review markdown file
        run: |
          mkdir -p content/reviews
          FILENAME="content/reviews/$(date +%s)-review.md"
          echo "---" > $FILENAME
          echo "name: ${{ github.event.inputs.name }}" >> $FILENAME
          echo "message: ${{ github.event.inputs.message }}" >> $FILENAME
          echo "rating: ${{ github.event.inputs.rating }}" >> $FILENAME
          echo "image: ${{ github.event.inputs.image }}" >> $FILENAME
          echo "---" >> $FILENAME
          echo "Review by ${{ github.event.inputs.name }}" >> $FILENAME

      - name: Commit and push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add content/reviews/
          git commit -m "Add review from ${{ github.event.inputs.name }}"
          git push
